### ISSUE TITLE
Could not login via normal login

### ISSUE THREAD

**Issue by fiher** [SoftUni-Internal/suls-issues-public#10]
After the previous issue about login with Google+ I tried to sign in with my username (fiherLuci) and password (You wish) and after hitting Sign In I am redirected to this page - 

![screenshot_4](https://user-images.githubusercontent.com/19430196/28366914-52714d34-6c97-11e7-8d67-648aa2fce149.png)

After I press 'Software University' I get -

![screenshot_3](https://user-images.githubusercontent.com/19430196/28366766-cc89f018-6c96-11e7-9488-b7240eefb700.png)

Browser - Opera (yes I know)

**Comment by veronika793** [comment]
The dev server was not configured yet.
