### ISSUE TITLE
No access to the educational materials of courses from the main program already paid previously

### ISSUE THREAD

**Issue by ghost** [SoftUni-Internal/suls-issues-public#100]
https://github.com/SoftUni-Internal/suls-issues-public/issues/88

Извинявам се много, но въпросът, дори затворен, все още не е решен! Някои изпити са след две седмици.

**Comment by rozay** [comment]
@villyj Please, use the convention template for logging issue and change the title. We need to know this information in order to investigate the problem: 
# Expected Behavior

# Actual Behavior

# Steps to Reproduce

1.
2.
3.

# Specifications

- Platform: [What platform are you using? SoftUni (https://softuni.org) / Software University (https://softuni.bg) / SoftUni Digital (https://digital.softuni.bg) / SoftUni Creative (https://creative.softuni.bg) / SoftUni Kids (https://kids.softuni.bg) / SoftUni Judge (https://judge.softuni.bg) / SoftUni Test System (https://softuni.bg:8080)]
- Browser used: [What browser are you using?]
- URL: [Is your problem related to a specific page?]
- Username: [What is your username?]

**Comment by ghost** [comment]
# Expected Behavior
The issue https://github.com/SoftUni-Internal/suls-issues-public/issues/88 is not solved despite the assurance given to be solved! Three weeks have passed. The first exams of the current modules are in two weeks. Is there going to be a solution at all and if yes when precisely?

The issue is (well-known): Automatic access to be granted to the course materials, videos, and life videos of current and past courses (despite sometimes appearing as open) from the main program the module of which has already been paid in the past in a previous instance. E.g. now there is no access to DB C#, DB Java, and PHP Web (all from the main program and now also as open) for a person that has paid for them in a previous instance.  

# Actual Behavior

There is no access to the courses from the previous point. The system asks for enrollment/payment.

# Steps to Reproduce

1. Please provide a deadline and give till then the access promised.
2.
3.

# Specifications

- Platform: https://softuni.org
- Browser used: any browser
- URL: no, general
- Username: villyjord (the issue is general)

**Comment by YanaSlavcheva** [comment]
@villyj We deployed a solution to the problem. Please, test, when possible. If the problem persists for You, plese give concrete example with a course, which resources you cannot access. Thank You!

**Comment by ghost** [comment]
Great! Seems fine. Everything is operational now. Many thanks.

**Comment by ghost** [comment]
Still a problem. Now the same story for JS Web - React.js. Open course at present, but some people (like me) that have paid for the module previously (me - May 2017) - no access to the materials. To avoid these issues, I think that a general solution is needed for all open courses now and in the future.

**Comment by YanaSlavcheva** [comment]
Hi. We have implemented general solution. Please, let me know where exactly you click to open the course and which resource is not accessible to you. Thank you!

**Comment by ghost** [comment]
Hi. Really impressed by the quick reply. I just click on the first presentation form the first lecture: https://softuni.bg/trainings/resources/officedocument/18916/presentation-reactjs-fundamentals-october2017. In the framework of the screen, the lecture's pptx opens (interestingly 30 min. ago even that was not possible), but when I click on the link below for the lecture itself to download it: https://softuni.bg/downloads/svn/js-web/Sept-2017/ReactJS/01.%20Course-Overview/01.%20Course-Overview.pptx, I cannot and it asks for enrollment and payment. For DB C# SQL Server that you (team) fixed 10 days ago I can download the lectures without any problems.  The video access is fine.

**Comment by YanaSlavcheva** [comment]
Thank you for letting us know for this problem. We became aware it not long ago. It is scheduled for fixing. We expect the solution to be deployed in the next two weeks. Will keep you posted :) We apologize for the inconvenience.
