### ISSUE TITLE
Forum answer editing as an admin(moderator)

### ISSUE THREAD

**Issue by shsimeonova** [SoftUni-Internal/suls-issues-public#101]
When you post a comment on a forum page and lock it, sometimes you want to edit your answer. You can't do that easily, because you first have to unlock the post and then edit your comment and repeat the locking process all over again. It would be nice **admins** and **moderators** to not have to do that.
# Expected Behavior
To be able to edit your answer as an admin or moderator regardless if the post is locked.
# Actual Behavior
![image](https://user-images.githubusercontent.com/19411274/31500652-a5511c48-af70-11e7-9f3a-7730e7dd408f.png)

# Steps to Reproduce

1. Find forum post
2. Post a comment
3. Lock the post
4. Try to edit your answer and see the repeating process 

# Specifications

- Platform: [What platform are you using? SoftUni (https://softuni.org)]
- Browser used: [Edge, Chrome, doesn't matter- 
- URL: [https://softuni.bg/forum/16581/materialite-sa-dostypni-samo-za-zapisani-potrebiteli-v-kursa-dotuk-s-bezplatnoto-obuchenie]
- Username: [Sim0o0na]

**Comment by rozay** [comment]
Moved in private repo
