### ISSUE TITLE
A link from the "comments" section of the user account does not refer to the own comment.

### ISSUE THREAD

**Issue by Stanimir-Hristov** [SoftUni-Internal/suls-issues-public#104]
Expected result: See your own comment.

Actual result: The first page opens and the comments are in chronological order.

 Steps to Reproduce:

1. Go to https://softuni.bg

2. Sign in to your account

3. Click on your own image (in my case the default image because I have not uploaded a photo)

4. Click on "forum"

5. Click on "comments"

6. Click on one of your own comments in the forum

Specifications

- Platform: https://softuni.bg
- Browser used: Google Chrome Version 61.0.3163.100 (Official Build) (64-bit) 
and Microsoft Edge 40.15063.674.0, Microsoft EdgeHTML 15.15063
- Username: st.hristov

**Comment by rozay** [comment]
@Stanimir-Hristov Thank you for the report, we'll fix that.

**Comment by veronika793** [comment]
The issue is fixed.
