### ISSUE TITLE
Missing courses under enrolled modules in the profile

### ISSUE THREAD

**Issue by ghost** [SoftUni-Internal/suls-issues-public#105]
# Expected Behavior
In my profile under enrolled modules at https://softuni.bg/users/profile/trainings/villyjord two modules are missing but should appear: C# web (re-enrolled now and paid half in September (grades to come) as well as previously enrolled in January (no grades there, skipped exams)) and PHP web (enrolled in January with one grade for PHP web dev basics and one skipped exam for PHP MVC)
# Actual Behavior
The two modules are missing, no record for them.
# Steps to Reproduce

1. It's good they to appear asap since some grades for them will come soon, e.g. C# Web Dev. Basics will be graded in the next days.
2.
3.

# Specifications

- Platform: https://softuni.org
- Browser used: any
- URL:  https://softuni.bg/users/profile/trainings/villyjord
- Username: villyjord

**Comment by YanaSlavcheva** [comment]
Hello. Thank You for this issue. We will investigate the problem.

**Comment by DesislavaG** [comment]
The same problem appears with user : nadiap . But here the missing modules and grades are - Tech Module May 20017 and Java Fundamentals September 2017.

**Comment by villyj** [comment]
Thanx! Great.

**Comment by ghost** [comment]
Thanx to all! Great.
