### ISSUE TITLE
Home page view error

### ISSUE THREAD

**Issue by badjok3** [SoftUni-Internal/suls-issues-public#109]
# Expected Behavior
Should display logged-in home page.
# Actual Behavior
Displays un-logged home page.

![untitled](https://user-images.githubusercontent.com/23360261/36003759-0da26728-0d38-11e8-8761-d9bd7d9e9317.png)

**Comment by KristianMariyanov** [comment]
This is by design and it's because you didn't have active training.
The "logged-in" screen is just a easy way to interact with your homework, exams, courses, etc. If you don't have trainings, there is no point to see empty boxes.
