### ISSUE TITLE
[Profile] Missing button for apply to university - partner

### ISSUE THREAD

**Issue by veronika793** [SoftUni-Internal/suls-issues-public#12]
environment: dev
username: verito898
os: Windows Pro 10 
browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
screen resolution: 1920x1080
when was discovered: 07.19.2017
priority: medium

Expected result: 
in the old profile there is button for applying to university partner

Actual result:
No button for applying to university partner

**Comment by rozay** [comment]
It is by design
