### ISSUE TITLE
[Profile] Profile show page - broken design in interest in programming on smaller resolutions

### ISSUE THREAD

**Issue by veronika793** [SoftUni-Internal/suls-issues-public#14]
environment: dev
username: verito898
os: Windows Pro 10 
browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
screen resolution: on resolutions <350px
when was discovered: 07.19.2017
priority: medium

steps to reproduce: go to https://dev.platform.softuni.bg:8080/users/profile/show

Expected result: Interest in programming text should not be cropped

Actual result: Interest in programming text is cropped on resolution >300 and <350px
![image](https://user-images.githubusercontent.com/7135591/28369905-9277e4e2-6ca1-11e7-8e10-8837bed9a838.png)

**Comment by rozay** [comment]
The font size of heading should be smaller like in the upper sections.

**Comment by TsenkoTsenov** [comment]
Related issue: https://github.com/SoftUni-Internal/suls-issues-public/issues/25
Fixed with: https://github.com/SoftUni-Internal/suls/commit/a375056378987746e145b7898bf3bb577d435d03
