### ISSUE TITLE
[Profile] Sentinel client can not be accessed

### ISSUE THREAD

**Issue by Iliev88** [SoftUni-Internal/suls-issues-public#16]
**os:** Windows 10 version 1703 (OS Build 15063.483)
**browser:** IE 11.483.15063.0
**screen resolution:** 1920x1080
**environment:** dev
**username:** Iliev88
**priority:** high

**steps to reproduce:**
1. Navigate to https://dev.platform.softuni.bg:8080/
2. Click on Profile picture
3. Click on"Sentinel client"

**actual result**
The user is unable to access Sentinel Client.

**expected result**
The user must be able to access and download Sentinel Client

![sentinel-client](https://user-images.githubusercontent.com/25150497/28371205-ff7ba2c4-6ca4-11e7-8f34-555f5266a8ad.png)

**Comment by veronika793** [comment]
It's specific only for the dev environment. Not an issue for the live server.
