### ISSUE TITLE
[Profile] Trainigns page - padding on course details 

### ISSUE THREAD

**Issue by veronika793** [SoftUni-Internal/suls-issues-public#17]
environment: dev
username: verito898
os: Windows 10 Pro 
browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
screen resolution:  <767
when was discovered: 07.19.2017
priority: medium

**steps to reproduce:**
- go to https://dev.platform.softuni.bg:8080/users/profile/forum?username=verito898
- Click on level
- Select course instance
- Select course
- Open any tab - exams or homework 
On resolutions less then 767px  there should be some padding /left and right/ between the text and container

**Expected result:**
On resolutions less then 767px the there should be some padding between text and container on left and right.

**Actual result:**
![image](https://user-images.githubusercontent.com/7135591/28373052-012d3006-6caa-11e7-9978-5c73e8e657b1.png)

**Comment by TsenkoTsenov** [comment]
Fixed with: https://github.com/SoftUni-Internal/suls/commit/2b48174631a72f4b49bfca98446856fb806eca13
