### ISSUE TITLE
[Profile] Profile image does not show

### ISSUE THREAD

**Issue by achobanov** [SoftUni-Internal/suls-issues-public#22]
environment: dev
username: achobanov
os: Linux Mint 18.2
browser:  Chrome v59.0.3071.115,  Firefox 54.0
screen resolution: 1920x1080
when was discovered: 07.20.2017

**steps to reproduce**
- login
- get to profile page, eg. https://dev.platform.softuni.bg:8080/users/profile/show/achobanov

**Expected result**:
My profile picture should appear.

**Actual result**:
Default image is displayed instead. 
![profile-pic](https://user-images.githubusercontent.com/1363532/28417916-862e3e18-6d62-11e7-8f83-536b7a4bbfe1.png)

The issue also appears in the site navbar:
![navbar-profile-pic](https://user-images.githubusercontent.com/1363532/28417922-8b6bfb2c-6d62-11e7-8f01-00cd4f2fdd40.png)

**Comment by veronika793** [comment]
Specific of the dev environment only. The profile pictures are not populated in the database for dev environment.
