### ISSUE TITLE
[Profile] Missing field "Номер на картата"

### ISSUE THREAD

**Issue by achobanov** [SoftUni-Internal/suls-issues-public#23]
environment: dev
username: achobanov
os: Linux Mint 18.2
browser: Chrome v59.0.3071.115, Firefox 54.0
screen resolution: 1920x1080
when was discovered: 07.20.2017

**steps to reproduce**
- login
- get to the profile page of currently logged in user

**Expected result:**
In the live version, this field is present in the profile page, on the right:
![card-number](https://user-images.githubusercontent.com/1363532/28418176-8132ff56-6d63-11e7-949b-5d98065b5a26.png)

**Actual result:**
It is nowhere to be found on the default profile page. Discard this if that is intended.

**Comment by veronika793** [comment]
Now it's in profile general info : `Номер на чип`.
