### ISSUE TITLE
[Profile] Profile menu should start from right

### ISSUE THREAD

**Issue by fiher** [SoftUni-Internal/suls-issues-public#26]
Browser - Opera
Resolution - 1536 x 864

Here is what I get when I select my profile - 
![screenshot_11](https://user-images.githubusercontent.com/19430196/28419380-749f94f8-6d67-11e7-9a84-d81999438967.png)

Current behavior - the menu leaves empty space on its right

Expected behavior - I think it will be better to start from the beginning of the screen as shown in the image. If this is the expected behavior disregard this issue.

**Comment by KristianMariyanov** [comment]
Try to imagine some ultra wide screen. Do you still think that it's a good idea to be on the right?
![image](https://user-images.githubusercontent.com/6886919/28419666-6f0b612e-6d68-11e7-9bc0-0657388e60e5.png)

**Comment by fiher** [comment]
Then another problem - why does the website leave so much empty space on wider screens?

**Comment by KristianMariyanov** [comment]
Because that's the design 😃

**Comment by KristianMariyanov** [comment]
You can ask GitHub dev team the same :)
