### ISSUE TITLE
Edit page - the button for editing linked profiles is not that obvious.

### ISSUE THREAD

**Issue by fiher** [SoftUni-Internal/suls-issues-public#27]
Browser - Opera
Resolution - 1536 x 864

When I go to edit my profile at first I see 2 buttons to go to another 2 pages for further edit of my profile. It is all good, but there is one another button redirecting to another page for editing the linked profiles (facebook,github etc.). In difference of the other two it has no description of what it does and it is small on the end of the screen barely showing. 

![screenshot_12](https://user-images.githubusercontent.com/19430196/28420053-938db65e-6d69-11e7-9721-a68afa16110a.png)

Expected behavior - being more descriptive of what it does considering the two other buttons. At first look I thought the only two options where the two buttons and I hat to press the button to see what it actually does.  If anything at least put it right before the line with linked profiles. This way I could make the connection that it is for editing this specific thing.

**Comment by veronika793** [comment]
We have edit sections for the platform and softuni separately - if you want to change any of that there are concrete pages for editing.
