### ISSUE TITLE
Company Logos missing

### ISSUE THREAD

**Issue by fiher** [SoftUni-Internal/suls-issues-public#29]
On this page - https://dev.platform.softuni.bg:8080/careers/companies the logos of the companies are missing 

![screenshot_3](https://user-images.githubusercontent.com/19430196/28420336-80a3ec10-6d6a-11e7-86f1-b4576fc42705.png)

Current behavior - doesnot show the logos of the companies

Expected behavior - to show the logos of the companies

**Comment by veronika793** [comment]
Specific for the dev environment.
