### ISSUE TITLE
[Profile]All edit sections for the profile are not working

### ISSUE THREAD

**Issue by veronika793** [SoftUni-Internal/suls-issues-public#3]
environment: dev
username: verito898
os: Windows Pro 10 
browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
screen resolution: 1920x1080
when was discovered: 07.19.2017
priority: high

**Steps to reproduce:**
- click on any edit button in user profile
https://dev.platform.softuni.bg/users/profile/show

**Expected result:**
Profile data should be editable

**Actual result:**
On clicking edit of any of the sections this page is loaded
![image](https://user-images.githubusercontent.com/7135591/28363707-382ec6d4-6c8a-11e7-85c9-8a8ee1ac08db.png)

**Comment by achobanov** [comment]
**Update**:
Most of the edits work. This error is visible when submitting "Промяна на общатата информация". However, the data is edited successfully. Other edits are almost working, with some issues.

**Comment by veronika793** [comment]
Duplicate issue of : https://github.com/SoftUni-Internal/suls-issues-public/issues/21
