### ISSUE TITLE
[Profile] Date cannot be edit

### ISSUE THREAD

**Issue by Iliev88** [SoftUni-Internal/suls-issues-public#31]
**os:** Windows 10 version 1703 (OS Build 15063.483)
**browser:** Chrome 59.0.3071.115 (Official Build) (64-bit)
**screen resolution:** 1920x1080
**environment:** dev
**username:** Iliev88
**priority:** high

**steps to reproduce:**
1. Navigate to https://dev.platform.softuni.bg:8080/
2. Click on Profile picture
3. Click on "General Information"
4. Click on "Edit"
5. Select a valid birth date
6. Click on "Save changes"

**actual result**
The user is unable to save changes made because the following error message "The field Дата на раждане must be a date."

**expected result**
The user must be able to save changes which she/he make with her/his birth date.

**note**
The same happens with editing dates the other sections of Profile - General Information

![date-must-be-valid](https://user-images.githubusercontent.com/25150497/28434271-7503d9ba-6d97-11e7-999c-d2665d1b40c1.png)

**Comment by veronika793** [comment]
Could not reproduce it. Can you add more specifics if possible - in you case i enter the same date and the date is edited successfully.

**Comment by Iliev88** [comment]
When clicking "Save" the user is redirected to "500 Unexpected error" screen but after refreshing she/he can observe the changes to her/his profile.

Cannot reproduce in the way it was reported. 

Maybe general editing profile data issue is responsible for that behavior.

**Comment by veronika793** [comment]
Yes that is described issue : https://github.com/SoftUni-Internal/suls-issues-public/issues/21
But thank you for the report.
