### ISSUE TITLE
[Profile] Missing warning message for missing date

### ISSUE THREAD

**Issue by Iliev88** [SoftUni-Internal/suls-issues-public#32]
**os:** Windows 10 version 1703 (OS Build 15063.483)
**browser:** Chrome 59.0.3071.115 (Official Build) (64-bit)
**screen resolution:** 1920x1080
**environment:** dev
**username:** Iliev88
**priority:** high

**steps to reproduce:**
1. Navigate to https://dev.platform.softuni.bg:8080/
2. Click on Profile picture
3. Click on "General Information"
4. Click on "Edit"
5. Type empty date
6. Click on "Save changes"

**actual result**
The user is unable to see a warning/error message that date is required field. SHe/he is redirected to nice error page.

**expected result**
The user must be able to see a nice warning/error message that Date is required field and must not be able to click on Save.

![missing-date](https://user-images.githubusercontent.com/25150497/28434622-abfa9520-6d98-11e7-99f8-31fda4dd617a.png)
![Uploading missing-date2.png…]()

**Comment by veronika793** [comment]
The date is not required field
