### ISSUE TITLE
[Profile] User can save profile changes without family name in English

### ISSUE THREAD

**Issue by Iliev88** [SoftUni-Internal/suls-issues-public#34]
**os:** Windows 10 version 1703 (OS Build 15063.483)
**browser:** Chrome 59.0.3071.115 (Official Build) (64-bit)
**screen resolution:** 1920x1080
**environment:** dev
**username:** Iliev88
**priority:** low

**steps to reproduce:**
1. Navigate to https://dev.platform.softuni.bg:8080/
2. Click on Profile picture
3. Click on "General Information"
4. Click on "Edit"
5. Type empty Family name in English
6. Click on "Save changes"

**actual result**
The user is unable to see a warning/error message that family name is required field. She/he is redirected to nice error page.

**expected result**
The user must be able to see a nice warning/error message that family name is required field and must not be able to click on Save. After refreshing the General Information page the field which was empty is properly shown on Profile page.

![family-empty](https://user-images.githubusercontent.com/25150497/28435289-08a1fd48-6d9b-11e7-9f4c-0aa19f046b9d.png)
![family-name-2](https://user-images.githubusercontent.com/25150497/28435290-08a4f5a2-6d9b-11e7-80ef-cdd9bfb7b188.png)

**Comment by veronika793** [comment]
When editing general information these field are not required and can be empty.
