### ISSUE TITLE
[Profile] Course information is wrong

### ISSUE THREAD

**Issue by Iliev88** [SoftUni-Internal/suls-issues-public#36]
**os:** Windows 10 version 1703 (OS Build 15063.483)
**browser:** Chrome 59.0.3071.115 (Official Build) (64-bit)
**screen resolution:** 1920x1080
**environment:** dev
**username:** Iliev88
**priority:** critical

**steps to reproduce:**
1. Navigate to https://dev.platform.softuni.bg:8080/
2. Click on Profile picture
3. Click on "Courses"
4. Click on "Open Courses"
5. Click on "QA Automation"
6. Click on "Exam"

**actual result**
The user is unable to see information for the given course instead she/he can see information for a course called QA Fundamentals

**expected result**
The user must be able to see information for the course that was clicked - QA Automation.

![courses](https://user-images.githubusercontent.com/25150497/28435727-e2ae2470-6d9c-11e7-816b-47b2887c976f.png)

**Comment by Iliev88** [comment]
A bit hard to reproduce.

Clicking on the two open courses changes the information..

**Comment by veronika793** [comment]
Could not reproduce it, but thanks for the report.
