### ISSUE TITLE
[Profile] Seminars table labels are in English

### ISSUE THREAD

**Issue by Iliev88** [SoftUni-Internal/suls-issues-public#37]
**os:** Windows 10 version 1703 (OS Build 15063.483)
**browser:** Chrome 59.0.3071.115 (Official Build) (64-bit)
**screen resolution:** 1920x1080
**environment:** dev
**username:** Iliev88
**priority:** trivial

**steps to reproduce:**
1. Navigate to https://dev.platform.softuni.bg:8080/
2. Click on Profile picture
3. Click on "Courses"
4. Click on "Seminars"

**actual result**
The user is able to see table labels in English.

**expected result**
The user must be able to see table labels in Bulgarian. 
![seminars](https://user-images.githubusercontent.com/25150497/28435815-40e1ca4c-6d9d-11e7-97ff-f3718de6f670.png)

![courses](https://user-images.githubusercontent.com/25150497/28435727-e2ae2470-6d9c-11e7-816b-47b2887c976f.png)

**Comment by TsenkoTsenov** [comment]
Fixed in: https://github.com/SoftUni-Internal/suls/commit/2b48174631a72f4b49bfca98446856fb806eca13
