### ISSUE TITLE
[Profile] Name written on certificate is not changed

### ISSUE THREAD

**Issue by Iliev88** [SoftUni-Internal/suls-issues-public#38]
**os:** Windows 10 version 1703 (OS Build 15063.483)
**browser:** Chrome 59.0.3071.115 (Official Build) (64-bit)
**screen resolution:** 1920x1080
**environment:** dev
**username:** Iliev88
**priority:** high

**precondition**
Change English name of the student.

**steps to reproduce:**
1. Navigate to https://dev.platform.softuni.bg:8080/
2. Click on Profile picture
3. Click on "Certificates"

**actual result**
The user is unable to see her/his edited new name written on her/his certificates.

**expected result**
The user must be able to see her/his name written on the certificates no matter fact that is is edited.

![name](https://user-images.githubusercontent.com/25150497/28436349-59d9a766-6d9f-11e7-99f8-6caab43233b4.png)
![name2](https://user-images.githubusercontent.com/25150497/28436328-4ccc2b5c-6d9f-11e7-886d-9aebb5291e70.png)

**Comment by veronika793** [comment]
The user names for the certificate will be changed when certificate is generated.
