### ISSUE TITLE
English version mixing languages

### ISSUE THREAD

**Issue by fiher** [SoftUni-Internal/suls-issues-public#39]
Enviorment - both dev and prod
Expected behavior - everything to be in English
Actual behavior - There is a mix between English and Bulgarian. Buttons and description titles are in English, but the rest is still in Bulgarian as shown below
![screenshot_4](https://user-images.githubusercontent.com/19430196/28436795-f37e37aa-6da0-11e7-94e1-3f9d78390975.png)

This applies to most pages with static text in them, but the page the screenshot was taken on was this one - https://dev.platform.softuni.bg:8080/careers/companies . Particularly bad because I tried to show it to an employer that doesnot speak bulgarian because he asked me if I new any other developers that could join his company. Since I am awesome I tried to show him this page to contact SoftUni. And it was bad...like really bad. So I suggest fixing all the pages (tell me if you want different issues for all of them) but this one in particular.

**Comment by veronika793** [comment]
Not a bug - there is section for eng/bg versions of all static sections - it's just that the team that fills the information does not yet translates the sections.
