### ISSUE TITLE
[English version] - Messages with different font and in Bulgarian 

### ISSUE THREAD

**Issue by fiher** [SoftUni-Internal/suls-issues-public#40]
Browser - Opera
When I select the English version here is how the messages look -

![screenshot_3](https://user-images.githubusercontent.com/19430196/28437284-ba3e8bd2-6da2-11e7-9f0e-ded22103b1f6.png)

The font is smaller and different while the message is still in Bulgarian.
Expected behavior - the message should be the same but in English.

Actual behavior - as shown in the screenshot - smaller font and still in Bulgarian.

**Comment by veronika793** [comment]
Not a bug -  it's just that the team that fills the information does not yet translate them.
