### ISSUE TITLE
Terms and conditions page not available

### ISSUE THREAD

**Issue by fiher** [SoftUni-Internal/suls-issues-public#41]
Browser  - Opera

Here is a screenshot when I try to go to Terms and Conditions from the footer menu - 

![screenshot_3](https://user-images.githubusercontent.com/19430196/28437446-5106b698-6da3-11e7-8d92-e936b543462d.png)

And here is a link - https://dev.platform.softuni.bg:8080/files/termsandconditions/terms-and-conditions-softuni-students-contract-rev-01.03.2017.pdf

Expected behavior - to show the Terms and Conditions

Actual behavior - error page.

**Comment by veronika793** [comment]
Specific for the dev environment. The file is not uploaded into the database on the dev server.
