### ISSUE TITLE
Trainers page - images not showing

### ISSUE THREAD

**Issue by fiher** [SoftUni-Internal/suls-issues-public#43]
Browser - Opera 

Here is what I see when I open this page - https://dev.platform.softuni.bg:8080/trainers from the footer menu. And here is a screenshot -
![screenshot_4](https://user-images.githubusercontent.com/19430196/28437569-c1d7fb84-6da3-11e7-8fcb-7621c7facd04.png)

Expected behavior - to show all images and not only Simo (#allTrainersAreEqual #bringImagesBack)

Actual behavior - images not showing.

**Comment by veronika793** [comment]
Specific for the dev environment. The images are not uploaded on dev server database.
