### ISSUE TITLE
Trainers page - guest trainers dont have description

### ISSUE THREAD

**Issue by fiher** [SoftUni-Internal/suls-issues-public#44]
When I look down at guest trainers they seem to have images, but no description available as shown in the screenshot - 

![screenshot_5](https://user-images.githubusercontent.com/19430196/28437669-2fa69f26-6da4-11e7-9fce-71d26e55a2ca.png)

Expected behavior - all trainers including guest trainers to have description.

Actual behavior - all guest trainers don't.

**Comment by veronika793** [comment]
Not a bug - they don't have description.
