### ISSUE TITLE
Blog page - images of posts not showing

### ISSUE THREAD

**Issue by fiher** [SoftUni-Internal/suls-issues-public#45]
Browser - Opera 

Images on this page - https://dev.platform.softuni.bg:8080/blog are not showing. Here is a screenshot -

![screenshot_6](https://user-images.githubusercontent.com/19430196/28437969-3636c7a2-6da5-11e7-98c9-db452f4c8628.png)

Expected behavior - the images to be available and shown

Actual behavior - the images are not.

**Comment by veronika793** [comment]
Specific for dev environment. The images are not uploaded into dev server database.
