### ISSUE TITLE
[Profile page]Some courses not showing.

### ISSUE THREAD

**Issue by fiher** [SoftUni-Internal/suls-issues-public#46]
Browser - Opera
Username - fiherLuci
When I go to my profile page and want to view my passed courses I am surprised to see that there are no courses for PHP Web. Here is a screenshot - 

![screenshot_7](https://user-images.githubusercontent.com/19430196/28438182-eb053aa6-6da5-11e7-9d8d-22df30e802d7.png)
Expected behavior - to show the courses PHP MVC and PHP Fundamentals from the module PHP Web that started in January.

Actual behavior - no courses found.

**Comment by achobanov** [comment]
This one duplicates an issue I reported: https://github.com/SoftUni-Internal/suls-issues-public/issues/28.
