### ISSUE TITLE
[Profile] The headings in General Info are in different colors

### ISSUE THREAD

**Issue by Iliev88** [SoftUni-Internal/suls-issues-public#47]
**os:** Windows 10 version 1703 (OS Build 15063.483)
**browser:** Chrome 59.0.3071.115 (Official Build) (64-bit)
**screen resolution:** 1920x1080
**environment:** dev
**username:** Iliev88
**priority:** trivial

**steps to reproduce:**
1. Navigate to https://dev.platform.softuni.bg:8080/
2. Click on Profile picture
3. Click on "General Information"

**actual result**
The headings in general profile information page are in different countries.

**expected result**
Are the heading supposed to be in the same color (blue or orange)?

![names](https://user-images.githubusercontent.com/25150497/28438291-523332f0-6da6-11e7-8aaf-3fc8fec91b6b.png)

**Comment by Iliev88** [comment]
**note**
Similar issue with the background color of sections "For me" and "Interests in programming"

![colors](https://user-images.githubusercontent.com/25150497/28438414-b0a9d622-6da6-11e7-9436-bab7f1d76cf0.png)

**Comment by veronika793** [comment]
Not a bug - that's the design.
