### ISSUE TITLE
[Profile] Social networks links do not work

### ISSUE THREAD

**Issue by Iliev88** [SoftUni-Internal/suls-issues-public#5]
**os:** Windows 10 version 1703 (OS Build 15063.483)
**browser:** Chrome 59.0.3071.115 (Official Build) (64-bit)
**screen resolution:** 1920x1080
**environment:** dev
**username:** Iliev88
**priority:** high

**steps to reproduce:**
1. Navigate to https://dev.platform.softuni.bg:8080/
2. Click on Profile picture
3. Click on any social network button

**actual result**
The user is unable to click on a given social network button.

**expected result**
The user must be able to be redirected to her/his page in the given social network when click on appropriate button.

**Comment by veronika793** [comment]
Could you provide and a screenshot, also is it when viewing other profiles, or your own ?

**Comment by Iliev88** [comment]
It was observed just before the deployment on 19th of July, so maybe should be closed.
