### ISSUE TITLE
[Profile] Open courses background is grey

### ISSUE THREAD

**Issue by Iliev88** [SoftUni-Internal/suls-issues-public#50]
**os:** Windows 10 version 1703 (OS Build 15063.483)
**browser:** Chrome 59.0.3071.115 (Official Build) (64-bit)
**screen resolution:** 1920x1080
**environment:** dev
**username:** Iliev88
**priority:** trivial

**steps to reproduce:**
1. Navigate to https://dev.platform.softuni.bg:8080/
2. Click on Profile picture
3. Click on "Courses"
4. Click on "Open Courses"

**actual result**
The background of the listed courses is grey.

**expected result**
The background of the listed courses must not be grey.

![grey](https://user-images.githubusercontent.com/25150497/28448525-4ec3ac04-6de1-11e7-8ab6-ca2d59ccdb2e.png)

**Comment by veronika793** [comment]
It's by design.
