### ISSUE TITLE
[Profile] Button "+Grade" redirects to teamwork page

### ISSUE THREAD

**Issue by Iliev88** [SoftUni-Internal/suls-issues-public#52]
**os:** Windows 10 version 1703 (OS Build 15063.483)
**browser:** Chrome 59.0.3071.115 (Official Build) (64-bit)
**screen resolution:** 1920x1080
**environment:** dev
**username:** Iliev88
**priority:** low

**steps to reproduce:**
1. Navigate to https://dev.platform.softuni.bg:8080/
2. Click on Profile picture
3. Click on "Courses"
4. Click on "Open Courses"
5. Click on "QA Automation"
6. Click on "Teamwork"
7. Click on "+Grade" on any user

**actual result**
The user is able to click on button called "+grade". She/he is redirected to teamwork page.

**expected result**
Is it intended that button to be clickable and to behave in that way?

![grade](https://user-images.githubusercontent.com/25150497/28448664-7f8d8390-6de2-11e7-88cc-fd65da8dcd01.png)

**Comment by veronika793** [comment]
From that page you can view the grade, doesn't look like an issue.
Thank you for the report.
