### ISSUE TITLE
[Profile] Profile menu is not attached to the right part of the screen in "Notifications"

### ISSUE THREAD

**Issue by Iliev88** [SoftUni-Internal/suls-issues-public#53]
**os:** Windows 10 version 1703 (OS Build 15063.483)
**browser:** Chrome 59.0.3071.115 (Official Build) (64-bit)
**screen resolution:** 1920x1080
**environment:** dev
**username:** Iliev88
**priority:** trivial

**steps to reproduce:**
1. Navigate to https://dev.platform.softuni.bg:8080/
2. Click on Profile picture
3. Click on "Notifications"

**actual result**
The user is unable to see profile menu attached to the right part of the screen. When clicks on profile picture it is shown.

**expected result**
The user must be able to see profile menu attached to the right part of the screen.

![not](https://user-images.githubusercontent.com/25150497/28448735-1806fc00-6de3-11e7-8aa2-d1daaa7ce95d.png)

**Comment by Iliev88** [comment]
Same behavior in:

- Settings;
- Teamwork

**Comment by achobanov** [comment]
I don't think these notifications work as they are supposed to. This is how the old profile menu looked like. Its not normal for all the sections to be revamped with a new look and feel, and keep the old setup for notifications.

**Comment by veronika793** [comment]
Not a bug since this is separate page.
