### ISSUE TITLE
[Mobile] - The curriculum page is with old information

### ISSUE THREAD

**Issue by fiher** [SoftUni-Internal/suls-issues-public#54]
enviorment - both dev and prod
Browser - Chrome
Resolution - 360 x 640
OS - Android
Mobile phone - HTC ONE M9

When I open this page - https://dev.platform.softuni.bg:8080/curriculum from my phone it shows old information and there is actually an image instead of actual information. I can't click on the modules and see what courses they have and more importantly - the information is old and misleading.  Here is a screenshot - 
![20271736_1461487617227778_121791119_n](https://user-images.githubusercontent.com/19430196/28450262-df575542-6dee-11e7-8fd4-f03fcced734f.png)

Expected behavior - to show the same information and have the same functionality as if it was opened from PC. 

Actual behavior - outdated information in the form of an image.

**Comment by Tuscann** [comment]
**Не е важно** програмата да се вижда правилно на smartphone.

**Comment by rozay** [comment]
Duplicate
