### ISSUE TITLE
[Profile] "Обучения" similar tab-sections are styled entirely different

### ISSUE THREAD

**Issue by achobanov** [SoftUni-Internal/suls-issues-public#57]
environment: dev
username: achobanov
os: Linux Mint 18.2
browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit), Firefox 54.0
screen resolution: 1920x1080
when was discovered: 07.20.2017

**Steps to reproduce**:
-Login
-Go to "Обучения" page for the logged in account.

**Expected result**:
In my opinion tabs with similar functionality are expected and are supposed to be styled in similar fashion.

**Actual result**:
As of now each each style has its own set of styles, they look very different from each other. The overall aesthetics could be improved a lot in my opinion. Also the usability suffers, because you have to click-expand multiple tabs, just to get a course data.

**Comment by veronika793** [comment]
It's by design, but thank you for the report.
