### ISSUE TITLE
[Profile]Forum page - questions, answers, comments - pagination styles broken

### ISSUE THREAD

**Issue by veronika793** [SoftUni-Internal/suls-issues-public#6]
environment: dev
username: verito898
os: Windows Pro 10 
browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
screen resolution: <1024px
when was discovered: 07.19.2017
priority: medium

**steps to reproduce:**
- go to https://dev.platform.softuni.bg:8080/users/profile/forum?username=verito898

**Expected result:**
 paggination bar should not look like this IMO.

**Actual result:**
On resolutions < 1024px  pagination seems a little broken.
![image](https://user-images.githubusercontent.com/7135591/28365522-a1cc8a2a-6c91-11e7-998b-e33477e85b31.png)

**Comment by rozay** [comment]
Related issue: https://github.com/SoftUni-Internal/suls-issues-public/issues/7
