### ISSUE TITLE
[Profile] Other profile data may not populate properly

### ISSUE THREAD

**Issue by achobanov** [SoftUni-Internal/suls-issues-public#62]
environment: dev
username: chobby
os: Linux Mint 18.2
browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit), Firefox 54.0
screen resolution: 1920x1080
when was discovered: 07.22.2017

**Steps to reproduce**:
- Login with chubby
- Look at other profiles, eg: https://dev.platform.softuni.bg:8080/users/profile/show/achobanov

**Expected result**:
Since achobanov is my account, it should have more data. When you login with achobanov - you will see that I have name in both Bulgarian and English language. Also I think certificates, other information and profile picture should be shown. 

**Actual result**:
As of now I can only see information about: City, Gender and Country. Names are listed as "No information", which as specified above is wrong:
![foreign-profile](https://user-images.githubusercontent.com/1363532/28493202-10791f70-6f1b-11e7-9409-38cfcb69b0f3.png)

**Comment by veronika793** [comment]
Are you sure you haven't edited your profile, before that? Now when you edit you profile you can set empty names for example. Please check if that is not the case, since i can not reproduce it for now.

**Comment by veronika793** [comment]
The information is shown if the user is signed as student in the system.
