### ISSUE TITLE
[Profile] Success notifications cannot be hidden

### ISSUE THREAD

**Issue by achobanov** [SoftUni-Internal/suls-issues-public#64]
environment: dev
username: achobanov
os: Linux Mint 18.2
browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit), Firefox 54.0
screen resolution: 1920x1080
when was discovered: 07.22.2017

**Steps to reproduce**:
- Login 
- Edit "Сертификат", "Интереси в програмирането", "Трудов стаж", "Или образование".

**Expected result**:
Notifications should hide automatically or should allow the user to hide them manually.

**Actual result**:
As of now success notifications are non-removable, unless you manually delete them with browser dev tools. There is no "remove" button and they do not hide automatically after a short period of time.

**Comment by veronika793** [comment]
Not a bug - by design.
