### ISSUE TITLE
[Profile] Certificates page - Publicity switch shows on other peoples profiles

### ISSUE THREAD

**Issue by TsenkoTsenov** [SoftUni-Internal/suls-issues-public#66]
os: Windows Pro 10
browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
environment: dev
username: TsenkoT
screen resolution: 1920x1080
when was discovered: 02.08.2017

**steps to reproduce:** 

- go to https://dev.platform.softuni.bg:8080/users/profile/certificates?username={someusername}

It shows certificate publicity switch even if you are not the owner, but it does not really change the certificate publicity.

![bad](https://user-images.githubusercontent.com/12273257/28879879-f58d0110-77ab-11e7-8c5b-4551fc00982e.png)

**Comment by KristianMariyanov** [comment]
Do not fix this issue. This functionality will be removed from the certificates.
