### ISSUE TITLE
Adding contest for lecturer via drop down optimisation

### ISSUE THREAD

**Issue by gogo4ds** [SoftUni-Internal/suls-issues-public#76]
When the pop up editor view is displayed, the drop down is showing only 5 contests, and if the user doesn't know the name or the number of the contest, cannot search dor it if it is not in the first 5.
![screenshot 1504776667](https://user-images.githubusercontent.com/15523019/30156887-8a11e4de-93c9-11e7-8a4a-7b6ca58bf9b3.jpg)

would be better if all the contests are loaded in the drop down list, via refactoring the code to not take first 5 contests. Also it could be further optimized to take only those contests in which the lecturer is not present.
![screenshot 1504776697](https://user-images.githubusercontent.com/15523019/30156974-c1a2d61a-93c9-11e7-807b-25bedb7e7b87.jpg)

**Comment by KristianMariyanov** [comment]
I think this is Combobox, not dropdown. So, you can type some text and filter the contests. IMO there is no need to step back to dropdown and load all contests.

**Comment by gogo4ds** [comment]
I understand, so issue is closed.

**Comment by KristianMariyanov** [comment]
BTW in this case, you could make the Prop(I guess is ContestId) nullable, to workaround the annoying zero at the input. 😸
