### ISSUE TITLE
What is the idea behind Glimpse menu?

### ISSUE THREAD

**Issue by D3A7H13** [SoftUni-Internal/suls-issues-public#86]
What is Glimpse in OJS and how do we use it?
![image](https://puu.sh/xyH3t/9ca28bbbfd.png)

**Comment by jicata** [comment]
[Glimpse](http://getglimpse.com/) is a real time diagnostics application. We use it for tracking data related to requests, server response times, etc. It's for debugging purposes, used by administrators mainly.

Does this answer your question?

**Comment by D3A7H13** [comment]
Yeah, thanks :)
