### ISSUE TITLE
[SoftUni web page] No current access to educational materials from previous courses which are now open

### ISSUE THREAD

**Issue by villyj** [SoftUni-Internal/suls-issues-public#88]
There is no access to the materials of the current instance of courses that appear now as open courses which a student from the main program has already enrolled in the past. E.g. DB C#/Java, JS Web, PHP Web. The front-office girls told me explicitly that there would be such.

**Comment by rozay** [comment]
Yes, the issue is solved. Soon it will be merged and deployed.
