### ISSUE TITLE
Fix description of course - Ruby on Rails – octomber 2017

### ISSUE THREAD

**Issue by Tuscann** [SoftUni-Internal/suls-issues-public#89]
https://youtu.be/2zRQ9ejnnog
The video shows broken description.
Link to the course: https://softuni.bg/trainings/1775/web-programming-with-ruby-on-rails-october-2017

**Comment by YanaSlavcheva** [comment]
In this repo we log issue in English only. So I am closing this one as `invalid`.

**Comment by Tuscann** [comment]
Ok you need screenshot of the problem
![image](https://user-images.githubusercontent.com/16596102/30661416-97da794a-9e4c-11e7-92c2-1b64015c309c.png)

**Comment by veronika793** [comment]
Fixed from administration.
