### ISSUE TITLE
Could not login via Google+

### ISSUE THREAD

**Issue by fiher** [SoftUni-Internal/suls-issues-public#9]
I opened the link provided in the readMe file and tried to login with Google. To specify - I pressed this button - 
![screenshot_10](https://user-images.githubusercontent.com/19430196/28366569-fa3730e4-6c95-11e7-8b56-a53daab65518.png)

After that I saw this - 
![screenshot_6](https://user-images.githubusercontent.com/19430196/28366577-0a397b50-6c96-11e7-8d9e-6427d02b3f03.png)

Browser - Opera (yes...I know) and Chrome
Resolution - 1536 x 864

**Comment by veronika793** [comment]
The server was not configured yet.
