### ISSUE TITLE
Judge problem

### ISSUE THREAD

**Issue by Tuscann** [SoftUni-Internal/suls-issues-public#92]
https://judge.softuni.bg/Contests/#!/List/ByCategory/66/Databases-Basics-Exercises

Why name is 
Data Definition And **Data Types** - Lab
Data Definition and **Datatypes** - Exersice

Wrong order:
 First need to come Lab after Exercise ??

Picture: https://gyazo.com/b1a2b32c63ec05545163aba09fdb8643

**Comment by shsimeonova** [comment]
@Tuscann Thank you for the report, it's fixed.

**Comment by rozay** [comment]
@Sim0o0na Can we close the issue?
